1.4.4

diff --git a/.github/workflows/build_macos.yml b/.github/workflows/build_macos.yml
--- a/.github/workflows/build_macos.yml
+++ b/.github/workflows/build_macos.yml
@@ -42,6 +42,24 @@ jobs:
           make lib CXXFLAGS="-arch arm64"
           mv libunrar.so libunrar.dylib
           ls -la
+      - name: Create entitlements.plist
+        run: |
+          cat > entitlements.plist << EOF
+          <?xml version="1.0" encoding="UTF-8"?>
+          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
+          <plist version="1.0">
+          <dict>
+              <key>com.apple.security.app-sandbox</key>
+              <true/>
+              <key>com.apple.security.files.downloads.read-write</key>
+              <true/>
+              <key>com.apple.security.files.user-selected.read-write</key>
+              <true/>
+          </dict>
+          </plist>
+          EOF
+          cat entitlements.plist
+          plutil -lint entitlements.plist || { echo "entitlements.plist is invalid"; exit 1; }
       - name: Build C++ with Qt5
         run: |
           mkdir build
@@ -73,24 +91,6 @@ jobs:
       - name: Use macdeployqt to deploy the app
         run: |
           /opt/homebrew/opt/qt@5/bin/macdeployqt build/SFDLSaugerPro.app -libpath=build/SFDLSaugerPro.app/Contents/Frameworks/ -verbose=2
-      - name: Create entitlements.plist
-        run: |
-          cat > entitlements.plist << EOF
-          <?xml version="1.0" encoding="UTF-8"?>
-          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
-          <plist version="1.0">
-          <dict>
-              <key>com.apple.security.app-sandbox</key>
-              <true/>
-              <key>com.apple.security.files.downloads.read-write</key>
-              <true/>
-              <key>com.apple.security.files.user-selected.read-write</key>
-              <true/>
-          </dict>
-          </plist>
-          EOF
-          cat entitlements.plist
-          plutil -lint entitlements.plist || { echo "entitlements.plist is invalid"; exit 1; }
       - name: Sign the app bundle
         run: |
           codesign --force --deep --entitlements entitlements.plist --sign "-" build/SFDLSaugerPro.app
